### ISSUE TITLE
small problem in documentation

### ISSUE THREAD

**Issue by ya3ya6** [sparklinlabs/perfect-resize#6]
in documentation it says for creating the handle you should use:
`new ResizeHandle(document.getElementById("#sidebar"), "right")`
but it should be:
`document.getElementById("sidebar")`
not:
`document.getElementById("#sidebar")`

**Comment by elisee** [comment]
Thanks for the report! I fixed it by using `querySelector` instead, which is what I tend to use.

Cheers!
